### ISSUE TITLE
Custom python is built without working _hashlib or _ssl on bionic

### ISSUE THREAD

**Issue by adborden** [GSA/datagov-deploy-common#10]
On Ubuntu bionic, the build succeeds, but it's no until you try to install pip dependencies for CKAN where you run into the error:

> "msg": "stdout: New python executable in /usr/lib/ckan-new/bin/python\nInstalling setuptools, pkg_resources, pip, wheel...\n  Complete output from command /usr/lib/ckan-new/bin/python - setuptools pkg_resources pip wheel:\n  ERROR:root:code for hash md5 was not found.\nTraceback (most recent call last):\n  File \"/usr/local/lib/python2.7.10/lib/python2.7/hashlib.py\", line 147, in <module>\n    globals()[__func_name] = __get_hash(__func_name)\n  File \"/usr/local/lib/python2.7.10/lib/python2.7/hashlib.py\", line 97, in __get_builtin_constructor\n    raise ValueError('unsupported hash type ' + name)\nValueError: unsupported hash type md5\nERROR:root:code for hash sha1 was not found.\nTraceback (most recent call last):\n  File \"/usr/local/lib/python2.7.10/lib/python2.7/hashlib.py\", line 147, in <module>\n    globals()[__func_name] = __get_hash(__func_name)\n  File \"/usr/local/lib/python2.7.10/lib/python2.7/hashlib.py\", line 97, in __get_builtin_constructor\n    raise ValueError('unsupported hash type ' + name)\nValueError: unsupported hash type sha1\nERROR:root:code for hash sha224 was not found.\nTraceback (most recent call last):\n  File \"/usr/local/lib/python2.7.10/lib/python2.7/hashlib.py\", line 147, in <module>\n    globals()[__func_name] = __get_hash(__func_name)\n  File \"/usr/local/lib/python2.7.10/lib/python2.7/hashlib.py\", line 97, in __get_builtin_constructor\n    raise ValueError('unsupported hash type ' + name)\nValueError: unsupported hash type sha224\nERROR:root:code for hash sha256 was not found.\nTraceback (most recent call last):\n  File \"/usr/local/lib/python2.7.10/lib/python2.7/hashlib.py\", line 147, in <module>\n    globals()[__func_name] = __get_hash(__func_name)\n  File \"/usr/local/lib/python2.7.10/lib/python2.7/hashlib.py\", line 97, in __get_builtin_constructor\n    raise ValueError('unsupported hash type ' + name)\nValueError: unsupported hash type sha256\nERROR:root:code for hash sha384 was not found.\nTraceback (most recent call last):\n  File \"/usr/local/lib/python2.7.10/lib/python2.7/hashlib.py\", line 147, in <module>\n    globals()[__func_name] = __get_hash(__func_name)\n  File \"/usr/local/lib/python2.7.10/lib/python2.7/hashlib.py\", line 97, in __get_builtin_constructor\n    raise ValueError('unsupported hash type ' + name)\nValueError: unsupported hash type sha384\nERROR:root:code for hash sha512 was not found.\nTraceback (most recent call last):\n  File \"/usr/local/lib/python2.7.10/lib/python2.7/hashlib.py\", line 147, in <module>\n    globals()[__func_name] = __get_hash(__func_name)\n  File \"/usr/local/lib/python2.7.10/lib/python2.7/hashlib.py\", line 97, in __get_builtin_constructor\n    raise ValueError('unsupported hash type ' + name)\nValueError: unsupported hash type sha512\nTraceback (most recent call last):\n  File \"<stdin>\", line 7, in <module>\n  File \"/usr/share/python-wheels/pip-9.0.1-py2.py3-none-any.whl/pip/__init__.py\", line 24, in <module>\n  File \"/usr/lib/ckan-new/share/python-wheels/urllib3-1.22-py2.py3-none-any.whl/urllib3/__init__.py\", line 8, in <module>\n  File \"/usr/lib/ckan-new/share/python-wheels/urllib3-1.22-py2.py3-none-any.whl/urllib3/connectionpool.py\", line 29, in <module>\n  File \"/usr/lib/ckan-new/share/python-wheels/urllib3-1.22-py2.py3-none-any.whl/urllib3/connection.py\", line 39, in <module>\n  File \"/usr/lib/ckan-new/share/python-wheels/urllib3-1.22-py2.py3-none-any.whl/urllib3/util/__init__.py\", line 6, in <module>\n  File \"/usr/lib/ckan-new/share/python-wheels/urllib3-1.22-py2.py3-none-any.whl/urllib3/util/ssl_.py\", line 7, in <module>\nImportError: cannot import name md5\n----------------------------------------\n...Installing setuptools, pkg_resources, pip, wheel...done.\nRunning virtualenv with interpreter /usr/local/lib/python2.7.10/bin/python\n\n:stderr: ERROR:root:code for hash md5 was not found.\nTraceback (most recent call last):\n  File \"/usr/local/lib/python2.7.10/lib/python2.7/hashlib.py\", line 147, in <module>\n    globals()[__func_name] = __get_hash(__func_name)\n  File \"/usr/local/lib/python2.7.10/lib/python2.7/hashlib.py\", line 97, in __get_builtin_constructor\n    raise ValueError('unsupported hash type ' + name)\nValueError: unsupported hash type md5\nERROR:root:code for hash sha1 was not found.\nTraceback (most recent call last):\n  File \"/usr/local/lib/python2.7.10/lib/python2.7/hashlib.py\", line 147, in <module>\n    globals()[__func_name] = __get_hash(__func_name)\n  File \"/usr/local/lib/python2.7.10/lib/python2.7/hashlib.py\", line 97, in __get_builtin_constructor\n    raise ValueError('unsupported hash type ' + name)\nValueError: unsupported hash type sha1\nERROR:root:code for hash sha224 was not found.\nTraceback (most recent call last):\n  File \"/usr/local/lib/python2.7.10/lib/python2.7/hashlib.py\", line 147, in <module>\n    globals()[__func_name] = __get_hash(__func_name)\n  File \"/usr/local/lib/python2.7.10/lib/python2.7/hashlib.py\", line 97, in __get_builtin_constructor\n    raise ValueError('unsupported hash type ' + name)\nValueError: unsupported hash type sha224\nERROR:root:code for hash sha256 was not found.\nTraceback (most recent call last):\n  File \"/usr/local/lib/python2.7.10/lib/python2.7/hashlib.py\", line 147, in <module>\n    globals()[__func_name] = __get_hash(__func_name)\n  File \"/usr/local/lib/python2.7.10/lib/python2.7/hashlib.py\", line 97, in __get_builtin_constructor\n    raise ValueError('unsupported hash type ' + name)\nValueError: unsupported hash type sha256\nERROR:root:code for hash sha384 was not found.\nTraceback (most recent call last):\n  File \"/usr/local/lib/python2.7.10/lib/python2.7/hashlib.py\", line 147, in <module>\n    globals()[__func_name] = __get_hash(__func_name)\n  File \"/usr/local/lib/python2.7.10/lib/python2.7/hashlib.py\", line 97, in __get_builtin_constructor\n    raise ValueError('unsupported hash type ' + name)\nValueError: unsupported hash type sha384\nERROR:root:code for hash sha512 was not found.\nTraceback (most recent call last):\n  File \"/usr/local/lib/python2.7.10/lib/python2.7/hashlib.py\", line 147, in <module>\n    globals()[__func_name] = __get_hash(__func_name)\n  File \"/usr/local/lib/python2.7.10/lib/python2.7/hashlib.py\", line 97, in __get_builtin_constructor\n    raise ValueError('unsupported hash type ' + name)\nValueError: unsupported hash type sha512\nTraceback (most recent call last):\n  File \"/usr/lib/python3/dist-packages/virtualenv.py\", line 2375, in <module>\n    main()\n  File \"/usr/lib/python3/dist-packages/virtualenv.py\", line 724, in main\n    symlink=options.symlink)\n  File \"/usr/lib/python3/dist-packages/virtualenv.py\", line 992, in create_environment\n    download=download,\n  File \"/usr/lib/python3/dist-packages/virtualenv.py\", line 922, in install_wheel\n    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)\n  File \"/usr/lib/python3/dist-packages/virtualenv.py\", line 817, in call_subprocess\n    % (cmd_desc, proc.returncode))\nOSError: Command /usr/lib/ckan-new/bin/python - setuptools pkg_resources pip wheel failed with error code 1\n"

In the configure/compile output from python, you'll see this output:

```
Failed to build these modules:
_hashlib           _ssl
```

**Comment by adborden** [comment]
This looks to be an incompatibility with a newer openssl, so upgrading to python 2.7.16 at least builds the modules. However, I'm running into another issue with virtualenv.

```
ubuntu@inventory-web1tf:~$ virtualenv -p /usr/local/lib/python2.7.16/bin/python venv
Running virtualenv with interpreter /usr/local/lib/python2.7.16/bin/python
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 21, in <module>
    import logging
  File "/usr/local/lib/python2.7.16/lib/python2.7/logging/__init__.py", line 26, in <module>
    import sys, os, time, cStringIO, traceback, warnings, weakref, collections
  File "/usr/local/lib/python2.7.16/lib/python2.7/weakref.py", line 14, in <module>
    from _weakref import (
ImportError: cannot import name _remove_dead_weakref
```

**Comment by adborden** [comment]
Ah, this error might have been a messed up ld.so.conf. I'm pretty sure switching to 2.7.16 is the correct fix.

**Comment by adborden** [comment]
Switched to 2.7.16 for bionic.
